name: Build documentation

on:
  workflow_dispatch:

jobs:
  mcss:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
          # macOS
          - os: macos-latest
          # Windows (commented out, untested)
          # - os: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
          sudo apt-get install -y doxygen ghostscript
          sudo apt-get install -y python3 python3-virtualenv
          sudo apt-get install -y texlive-base
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-fonts-extra
          sudo apt-get install -y texlive-fonts-recommended dvisvgm

      - name: Set up dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja doxygen ghostscript python virtualenv
          brew install dvisvgm

      - name: Configure CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DWITH_DOCS=ON \
            -DUSE_DOC_TOOL=MCSS

      - name: Build
        run: cmake --build build --target doc

