name: Clang-Tidy Analysis

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Minimal configuration of libarcstk

      - name: Set up dependencies (ubuntu-latest == 24.04 "Noble Noumbat")
        run: |
          sudo apt-get install -y cmake ninja-build clang-tidy

      - name: Configure with clang-tidy
        run: |
          cmake -B build

      - name: Create clang-tidy report
        run: |
          cmake --build build --target libarcstk_clang-tidy-workflow

